# lib导入

In [1]:
# export
import os
from code.config import * 
from loguru import logger
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 100)  # 设置显示数据的最大列数，防止出现省略号…，导致数据显示不全
pd.set_option('expand_frame_repr', False)  # 当列太多时不自动换行

from sklearn.metrics import f1_score

# load data

In [2]:
train_user_feat = pd.read_pickle(os.path.join(args.DATA_DIR,'data_gen/train_user_feat.pkl'))

test_user_feat = pd.read_pickle(os.path.join(args.DATA_DIR,'data_gen/test_user_feat.pkl'))

In [3]:
train_voc_feat = pd.read_pickle(os.path.join(args.DATA_DIR,'data_gen/df_train_voc.pkl'))

test_voc_feat = pd.read_pickle(os.path.join(args.DATA_DIR,'data_gen/df_test_voc.pkl'))

train_sms_feat = pd.read_pickle(os.path.join(args.DATA_DIR,'data_gen/df_train_sms.pkl'))

test_sms_feat = pd.read_pickle(os.path.join(args.DATA_DIR,'data_gen/df_train_sms.pkl'))

In [4]:
train_app_feat = pd.read_pickle(os.path.join(args.DATA_DIR,'data_gen/df_train_app.pkl'))

test_app_feat = pd.read_pickle(os.path.join(args.DATA_DIR,'data_gen/df_train_app.pkl'))

In [5]:
df_train = pd.merge(pd.merge(pd.merge(train_user_feat, train_voc_feat, on='phone_no_m', how='left'),
                    train_sms_feat, on='phone_no_m', how='left'),
                   train_app_feat, on='phone_no_m', how='left')

df_test = pd.merge(pd.merge(pd.merge(test_user_feat, test_voc_feat, on='phone_no_m', how='left'),
                    test_sms_feat, on='phone_no_m', how='left'),
                   test_app_feat, on='phone_no_m', how='left')

In [6]:
df_train.head(2)

                                          phone_no_m city_name county_name  idcard_cnt     arpu  label  opposite_no_m_count_x  opposite_no_m_nunique_x  calltype_id_nunique_x  city_name_nunique  county_name_nunique  imei_m_nunique  hour_nunique_x  day_nunique_x  weekday_nunique_x  call_dur_sum  call_dur_mean  call_dur_median  call_dur_max  call_dur_min  call_dur_std  time_interval_sum_x  time_interval_mean_x  time_interval_median_x  time_interval_max_x  time_interval_min_x  time_interval_std_x  opposite_no_m_count_nunique_ratio_x  opposite_no_m_count_calltype_id1_x  opposite_no_m_count_calltype_id2_x  opposite_no_m_count_calltype_id3  opposite_no_m_nunique_calltype_id1_x  opposite_no_m_nunique_calltype_id2_x  opposite_no_m_nunique_calltype_id3  city_name_nunique_calltype_id1  city_name_nunique_calltype_id2  city_name_nunique_calltype_id3  county_name_nunique_calltype_id1  county_name_nunique_calltype_id2  county_name_nunique_calltype_id3  imei_m_nunique_calltype_id1  imei_m_nunique_calltype_id2  imei_m_nunique_calltype_id3  hour_nunique_calltype_id1_x  hour_nunique_calltype_id2_x  hour_nunique_calltype_id3  day_nunique_calltype_id1_x  day_nunique_calltype_id2_x  day_nunique_calltype_id3  weekday_nunique_calltype_id1_x  ...  time_interval_sum_weekday2_y  time_interval_sum_weekday3_y  time_interval_sum_weekday4_y  time_interval_sum_weekday5_y  time_interval_sum_weekday6_y  time_interval_mean_weekday0_y  time_interval_mean_weekday1_y  time_interval_mean_weekday2_y  time_interval_mean_weekday3_y  time_interval_mean_weekday4_y  time_interval_mean_weekday5_y  time_interval_mean_weekday6_y  time_interval_median_weekday0_y  time_interval_median_weekday1_y  time_interval_median_weekday2_y  time_interval_median_weekday3_y  time_interval_median_weekday4_y  time_interval_median_weekday5_y  time_interval_median_weekday6_y  time_interval_max_weekday0_y  time_interval_max_weekday1_y  time_interval_max_weekday2_y  time_interval_max_weekday3_y  time_interval_max_weekday4_y  time_interval_max_weekday5_y  time_interval_max_weekday6_y  time_interval_min_weekday0_y  time_interval_min_weekday1_y  time_interval_min_weekday2_y  time_interval_min_weekday3_y  time_interval_min_weekday4_y  time_interval_min_weekday5_y  time_interval_min_weekday6_y  time_interval_std_weekday0_y  time_interval_std_weekday1_y  time_interval_std_weekday2_y  time_interval_std_weekday3_y  time_interval_std_weekday4_y  time_interval_std_weekday5_y  time_interval_std_weekday6_y  busi_name_count  busi_name_nunique      flow_sum  flow_mean  flow_median     flow_max  flow_min    flow_std  busi_name_count_nunique_ratio  flow_sum_nunique_ratio
0  672ddbf02a5544d32e4ecc9433b1981bffe23bf912273a...        绵阳       江油分公司           1  45.1325      0                  283.0                     36.0                    2.0                4.0                 10.0             2.0            20.0           31.0                7.0       19897.0      94.351515             34.0        1989.0           4.0    230.974699            2837660.0          39967.042254                 12216.0             324249.0                 27.0         60492.113458                             7.861111                               145.0                               138.0                               0.0                                  29.0                                  26.0                                 0.0                             2.0                             4.0                             0.0                               5.0                              10.0                               0.0                          2.0                          1.0                          0.0                         19.0                         16.0                        0.0                        29.0                        28.0                       0.0                             7.0  ...                      478772.0                      449054.0                      435078.0                      518289.0                      438572.0                   46148.666667                   48558.538462                   21181.705882                   28738.545455                       17402.20                   28793.833333                   26335.200000                          22285.0                          13462.0                           6682.5                          12234.5                           4326.0                          27322.5                           9773.0                      193700.0                      266685.0                      155769.0                      117553.0                      181908.0                      144648.0                      163716.0                           1.0                           0.0                           0.0                           0.0                           0.0                           6.0                           0.0                  63169.676060                  83427.737103                  35556.017247                  40103.561960                  35791.997629                  51459.550848                  42113.569046              150                143   4530.782520  27.459288     0.262863  1544.715554  0.000839  133.664779                       1.100000               32.831757
1  5e1272273e041e82cb275ae877710be98cdaf5b0a8f34d...        德阳       旌阳分公司           1  63.9375      0                   41.0                     20.0                    2.0                1.0                  2.0             1.0            14.0           18.0                7.0        3667.0     131.250000             55.0         615.0          13.0    186.066134            3108179.0         282561.727273                244433.0             999307.0              12741.0        284351.362548                             2.733333                                17.0                                31.0                               0.0                                   8.0                                  16.0                                 0.0                             1.0                             1.0                             0.0                               2.0                               2.0                               0.0                          1.0                          1.0                          0.0                          8.0                         13.0                        0.0                        10.0                        16.0                       0.0                             5.0  ...                      445960.0                      445055.0                      412110.0                      464791.0                      481180.0                   19158.769231                   12678.413043                    7558.644068                   11926.466667                       14639.28                   13740.310345                    8808.275862                            844.0                            127.5                             24.0                            703.5                            402.0                             89.0                             26.0                      102066.0                      253520.0                       90168.0                       94454.0                       90882.0                      137887.0                       92871.0                           0.0                           0.0                           0.0                           0.0                           0.0                           0.0                           0.0                  32451.315213                  40218.857243                  18538.342994                  23419.043826                  27975.901068                  30207.979613                  18526.651681              214                187  13169.332113  53.662528     0.586251  3611.522758  0.001075  264.088577                       1.202247               83.350203

[2 rows x 1102 columns]

In [7]:
df_test.head(2)

                                          phone_no_m city_name county_name  idcard_cnt  arpu  opposite_no_m_count_x  opposite_no_m_nunique_x  calltype_id_nunique_x  city_name_nunique  county_name_nunique  imei_m_nunique  hour_nunique_x  day_nunique_x  weekday_nunique_x  call_dur_sum  call_dur_mean  call_dur_median  call_dur_max  call_dur_min  call_dur_std  time_interval_sum_x  time_interval_mean_x  time_interval_median_x  time_interval_max_x  time_interval_min_x  time_interval_std_x  opposite_no_m_count_nunique_ratio_x  opposite_no_m_count_calltype_id1_x  opposite_no_m_count_calltype_id2_x  opposite_no_m_count_calltype_id3  opposite_no_m_nunique_calltype_id1_x  opposite_no_m_nunique_calltype_id2_x  opposite_no_m_nunique_calltype_id3  city_name_nunique_calltype_id1  city_name_nunique_calltype_id2  city_name_nunique_calltype_id3  county_name_nunique_calltype_id1  county_name_nunique_calltype_id2  county_name_nunique_calltype_id3  imei_m_nunique_calltype_id1  imei_m_nunique_calltype_id2  imei_m_nunique_calltype_id3  hour_nunique_calltype_id1_x  hour_nunique_calltype_id2_x  hour_nunique_calltype_id3  day_nunique_calltype_id1_x  day_nunique_calltype_id2_x  day_nunique_calltype_id3  weekday_nunique_calltype_id1_x  weekday_nunique_calltype_id2_x  ...  time_interval_sum_weekday2_y  time_interval_sum_weekday3_y  time_interval_sum_weekday4_y  time_interval_sum_weekday5_y  time_interval_sum_weekday6_y  time_interval_mean_weekday0_y  time_interval_mean_weekday1_y  time_interval_mean_weekday2_y  time_interval_mean_weekday3_y  time_interval_mean_weekday4_y  time_interval_mean_weekday5_y  time_interval_mean_weekday6_y  time_interval_median_weekday0_y  time_interval_median_weekday1_y  time_interval_median_weekday2_y  time_interval_median_weekday3_y  time_interval_median_weekday4_y  time_interval_median_weekday5_y  time_interval_median_weekday6_y  time_interval_max_weekday0_y  time_interval_max_weekday1_y  time_interval_max_weekday2_y  time_interval_max_weekday3_y  time_interval_max_weekday4_y  time_interval_max_weekday5_y  time_interval_max_weekday6_y  time_interval_min_weekday0_y  time_interval_min_weekday1_y  time_interval_min_weekday2_y  time_interval_min_weekday3_y  time_interval_min_weekday4_y  time_interval_min_weekday5_y  time_interval_min_weekday6_y  time_interval_std_weekday0_y  time_interval_std_weekday1_y  time_interval_std_weekday2_y  time_interval_std_weekday3_y  time_interval_std_weekday4_y  time_interval_std_weekday5_y  time_interval_std_weekday6_y  busi_name_count  busi_name_nunique  flow_sum  flow_mean  flow_median  flow_max  flow_min  flow_std  busi_name_count_nunique_ratio  flow_sum_nunique_ratio
0  22d522340df77e2252c1a4d92b4bcb00d515e36f3ec6bf...        成都       金牛分公司           1   9.0                    NaN                      NaN                    NaN                NaN                  NaN             NaN             NaN            NaN                NaN           NaN            NaN              NaN           NaN           NaN           NaN                  NaN                   NaN                     NaN                  NaN                  NaN                  NaN                                  NaN                                 NaN                                 NaN                               NaN                                   NaN                                   NaN                                 NaN                             NaN                             NaN                             NaN                               NaN                               NaN                               NaN                          NaN                          NaN                          NaN                          NaN                          NaN                        NaN                         NaN                         NaN                       NaN                             NaN                             NaN  ...                           NaN                           NaN                           NaN                           NaN                           NaN                            NaN                            NaN                            NaN                            NaN                            NaN                            NaN                            NaN                              NaN                              NaN                              NaN                              NaN                              NaN                              NaN                              NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN              NaN                NaN       NaN        NaN          NaN       NaN       NaN       NaN                            NaN                     NaN
1  5220d4b8429bdba3971a7b46a088c6b8fa6710f4060759...      天府新区      天府直属部门           1   NaN                   33.0                     23.0                    1.0                0.0                  0.0             2.0            10.0            4.0                4.0       17866.0     541.393939            240.0        3505.0           2.0    834.616938            1455108.0             45472.125                   412.0            1297878.0                 18.0        229069.824798                             1.434783                                33.0                                 0.0                               0.0                                  23.0                                   0.0                                 0.0                             0.0                             0.0                             0.0                               0.0                               0.0                               0.0                          2.0                          0.0                          0.0                         10.0                          0.0                        0.0                         4.0                         0.0                       0.0                             4.0                             0.0  ...                           NaN                           NaN                           NaN                           NaN                           NaN                            NaN                            NaN                            NaN                            NaN                            NaN                            NaN                            NaN                              NaN                              NaN                              NaN                              NaN                              NaN                              NaN                              NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN              NaN                NaN       NaN        NaN          NaN       NaN       NaN       NaN                            NaN                     NaN

[2 rows x 1101 columns]

In [8]:
df_test.shape

(2045, 1101)

In [9]:
df_train = df_train.set_index('phone_no_m')
df_test = df_test.set_index('phone_no_m')

In [33]:
# df_train = df_train.drop(columns='arpu county_name busi_name_te_min busi_name_te_max busi_name_te_mean busi_name_te_std busi_name_te_median'.split())

# df_test = df_test.drop(columns='arpu county_name busi_name_te_min busi_name_te_max busi_name_te_mean busi_name_te_std busi_name_te_median'.split())

# train

In [10]:
from sklearn.model_selection import KFold
folds = KFold(n_splits=5, shuffle=True, random_state=2020)

In [11]:
param = {
    'boosting_type': 'gbdt',
    'objective': 'binary',
    'metric': ['binary_logloss', 'accuracy'], 
    'num_leaves': 300,  
    'min_data_in_leaf': 500,  
    'learning_rate': 0.05,  
    'feature_fraction': 0.8,  
    'bagging_fraction': 0.8,  
    'bagging_freq': 5,  
    'lambda_l1': 0.4,  
    'lambda_l2': 0.5,  
    'min_gain_to_split': 0.2,  
    'verbose': -1,
    'num_threads':-1,
#     'scale_pos_weight':2,
}

In [12]:
import lightgbm as lgb

In [14]:
predictions = np.zeros([len(df_test)])
for fold_,(trn_idx,val_idx) in enumerate(folds.split(df_train)):
    X_train, y_train = df_train.iloc[trn_idx].copy(), df_train.label.iloc[trn_idx].copy()
    X_val, y_val = df_train.drop(columns='label').iloc[val_idx], df_train.label.iloc[val_idx]
    
    city_name_series = X_train.groupby('city_name')['label'].mean()
    county_name_series = X_train.groupby('county_name')['label'].mean()
    
    del X_train['label']
    
    X_train['city_name'] = X_train['city_name'].map(city_name_series, na_action='ignore')


    X_train['county_name'] = X_train['county_name'].map(county_name_series, na_action='ignore')

    X_val['city_name'] = X_val['city_name'].map(city_name_series, na_action='ignore')
    X_val['county_name'] = X_val['county_name'].map(county_name_series, na_action='ignore')
    df_test['city_name'] = df_test['city_name'].map(city_name_series, na_action='ignore')
    df_test['county_name'] = df_test['county_name'].map(county_name_series, na_action='ignore')
    
    
    trn_data = lgb.Dataset(X_train, y_train)
    val_data = lgb.Dataset(X_val, y_val)
    
    num_round = 1000
    # callback
    def reset_metrics():
        def callback(env):
            if env.iteration % 100 == 1:
                rs = pd.Series(env.model.predict(X_val).tolist()).map(round)
                print(f'{env.iteration} predict...{f1_score(y_val.tolist(), rs.tolist(), average="macro")}')
#                 print(f'{env.iteration} predict...{accuracy_score(y_val.values, rs.values)}')
        callback.before_iteration = False
        callback.order = 0
        return callback
    
    clf = lgb.train(param, 
                    trn_data, 
                    num_round, 
                    valid_sets = [trn_data, val_data], 
                    verbose_eval = 100, 
                    early_stopping_rounds = 200,
                    callbacks=[reset_metrics()])
    rs = pd.Series(clf.predict(X_val).tolist()).map(round)
    print(f'{num_round} predict...{f1_score(y_val.tolist(), rs.tolist(), average="macro")}')
    
    importance = clf.feature_importance()
    feature_name = clf.feature_name()
    feature_importance = pd.DataFrame({'feature_name':feature_name,'importance':importance} ).sort_values(by='importance',ascending=False)
#     feature_importance.to_csv('feature_importance_{}.csv'.format(idx+1),index=None)
    print(feature_importance.head(10))
    #oof[val_idx] = clf.predict(X_train[val_idx], num_iteration=clf.best_iteration)    
    predictions += clf.predict(df_test, num_iteration=clf.best_iteration) / folds.n_splits

Training until validation scores don't improve for 200 rounds
1 predict...0.3980295566502463
[100]	training's binary_logloss: 0.189728	valid_1's binary_logloss: 0.219685
101 predict...0.9051298036770846
[200]	training's binary_logloss: 0.1422	valid_1's binary_logloss: 0.200002
201 predict...0.9196799969952769
[300]	training's binary_logloss: 0.114119	valid_1's binary_logloss: 0.198341
301 predict...0.9190162505467396
[400]	training's binary_logloss: 0.0923026	valid_1's binary_logloss: 0.197401
401 predict...0.9210345404788878
[500]	training's binary_logloss: 0.0754756	valid_1's binary_logloss: 0.197911
501 predict...0.9221515761734289
Early stopping, best iteration is:
[340]	training's binary_logloss: 0.104446	valid_1's binary_logloss: 0.196508
1000 predict...0.9190162505467396
                                    feature_name  importance
1                                    county_name          73
3                                           arpu          50
29          opposite_no_m_nunique_calltype_id1_x          50
713                      opposite_no_m_nunique_y          28
1094                                 flow_median          26
721                          time_interval_max_y          25
5                        opposite_no_m_nunique_x          23
1097                                    flow_std          22
742             time_interval_max_calltype_id2_y          20
747   opposite_no_m_count_calltype_id1_2_ratio_y          19
Training until validation scores don't improve for 200 rounds
1 predict...0.41156626506024097
[100]	training's binary_logloss: 0.191454	valid_1's binary_logloss: 0.20755
101 predict...0.9071814093830222
[200]	training's binary_logloss: 0.143402	valid_1's binary_logloss: 0.182727
201 predict...0.9190554480125164
[300]	training's binary_logloss: 0.114838	valid_1's binary_logloss: 0.178419
301 predict...0.9251262894115775
[400]	training's binary_logloss: 0.0934852	valid_1's binary_logloss: 0.177226
401 predict...0.9231026756118904
[500]	training's binary_logloss: 0.0762984	valid_1's binary_logloss: 0.17945
501 predict...0.9241813950292139
[600]	training's binary_logloss: 0.0631677	valid_1's binary_logloss: 0.181239
Early stopping, best iteration is:
[401]	training's binary_logloss: 0.0932906	valid_1's binary_logloss: 0.177151
1000 predict...0.9221595655633262
                              feature_name  importance
1                              county_name          68
3                                     arpu          56
29    opposite_no_m_nunique_calltype_id1_x          50
2                               idcard_cnt          35
1094                           flow_median          28
721                    time_interval_max_y          27
5                  opposite_no_m_nunique_x          25
713                opposite_no_m_nunique_y          24
932          time_interval_median_hour15_y          22
1097                              flow_std          18
Training until validation scores don't improve for 200 rounds
1 predict...0.40814348036839554
[100]	training's binary_logloss: 0.184658	valid_1's binary_logloss: 0.226423
101 predict...0.9017835596603998
[200]	training's binary_logloss: 0.136124	valid_1's binary_logloss: 0.208299
201 predict...0.9104550865098751
[300]	training's binary_logloss: 0.107288	valid_1's binary_logloss: 0.208923
301 predict...0.9113675958188152
[400]	training's binary_logloss: 0.086686	valid_1's binary_logloss: 0.209644
401 predict...0.9150310402195796
[500]	training's binary_logloss: 0.0703379	valid_1's binary_logloss: 0.209124
501 predict...0.9133372048006194
Early stopping, best iteration is:
[322]	training's binary_logloss: 0.102137	valid_1's binary_logloss: 0.207272
1000 predict...0.9133372048006194
                                    feature_name  importance
1                                    county_name          72
3                                           arpu          53
721                          time_interval_max_y          35
5                        opposite_no_m_nunique_x          34
29          opposite_no_m_nunique_calltype_id1_x          33
713                      opposite_no_m_nunique_y          26
9                                 imei_m_nunique          24
1097                                    flow_std          21
747   opposite_no_m_count_calltype_id1_2_ratio_y          19
2                                     idcard_cnt          19
Training until validation scores don't improve for 200 rounds
1 predict...0.4023494860499266
[100]	training's binary_logloss: 0.18866	valid_1's binary_logloss: 0.218577
101 predict...0.9058463426916783
[200]	training's binary_logloss: 0.139949	valid_1's binary_logloss: 0.202463
201 predict...0.9195550550057863
[300]	training's binary_logloss: 0.111545	valid_1's binary_logloss: 0.200692
301 predict...0.9224480880411949
[400]	training's binary_logloss: 0.0896465	valid_1's binary_logloss: 0.203075
401 predict...0.92312619069642
Early stopping, best iteration is:
[260]	training's binary_logloss: 0.121893	valid_1's binary_logloss: 0.199637
1000 predict...0.9205565779934193
                                    feature_name  importance
1                                    county_name          59
3                                           arpu          50
721                          time_interval_max_y          38
29          opposite_no_m_nunique_calltype_id1_x          37
5                        opposite_no_m_nunique_x          30
2                                     idcard_cnt          23
1097                                    flow_std          17
38                   imei_m_nunique_calltype_id1          17
948                    time_interval_max_hour7_y          16
747   opposite_no_m_count_calltype_id1_2_ratio_y          16
Training until validation scores don't improve for 200 rounds
1 predict...0.40117704757233935
[100]	training's binary_logloss: 0.185688	valid_1's binary_logloss: 0.226452
101 predict...0.9046738435259614
[200]	training's binary_logloss: 0.137356	valid_1's binary_logloss: 0.211469
201 predict...0.9100849842378055
[300]	training's binary_logloss: 0.109618	valid_1's binary_logloss: 0.209517
301 predict...0.9142818363921148
[400]	training's binary_logloss: 0.0888766	valid_1's binary_logloss: 0.213031
401 predict...0.911487600406889
Early stopping, best iteration is:
[253]	training's binary_logloss: 0.121834	valid_1's binary_logloss: 0.208476
1000 predict...0.9113612999062507
                                    feature_name  importance
1                                    county_name          59
3                                           arpu          57
29          opposite_no_m_nunique_calltype_id1_x          37
713                      opposite_no_m_nunique_y          29
721                          time_interval_max_y          28
747   opposite_no_m_count_calltype_id1_2_ratio_y          22
2                                     idcard_cnt          22
5                        opposite_no_m_nunique_x          22
1094                                 flow_median          22
21                        time_interval_median_x          18

In [15]:
df_test.shape

(2045, 1100)

In [16]:
predictions

array([0.31187339, 0.85425379, 0.0062086 , ..., 0.00741361, 0.00629917,
       0.31295333])

In [17]:
df_test['label'] = pd.Series(predictions).map(round).tolist()

In [18]:
df_test.head(2)

                                                    city_name  county_name  idcard_cnt  arpu  opposite_no_m_count_x  opposite_no_m_nunique_x  calltype_id_nunique_x  city_name_nunique  county_name_nunique  imei_m_nunique  hour_nunique_x  day_nunique_x  weekday_nunique_x  call_dur_sum  call_dur_mean  call_dur_median  call_dur_max  call_dur_min  call_dur_std  time_interval_sum_x  time_interval_mean_x  time_interval_median_x  time_interval_max_x  time_interval_min_x  time_interval_std_x  opposite_no_m_count_nunique_ratio_x  opposite_no_m_count_calltype_id1_x  opposite_no_m_count_calltype_id2_x  opposite_no_m_count_calltype_id3  opposite_no_m_nunique_calltype_id1_x  opposite_no_m_nunique_calltype_id2_x  opposite_no_m_nunique_calltype_id3  city_name_nunique_calltype_id1  city_name_nunique_calltype_id2  city_name_nunique_calltype_id3  county_name_nunique_calltype_id1  county_name_nunique_calltype_id2  county_name_nunique_calltype_id3  imei_m_nunique_calltype_id1  imei_m_nunique_calltype_id2  imei_m_nunique_calltype_id3  hour_nunique_calltype_id1_x  hour_nunique_calltype_id2_x  hour_nunique_calltype_id3  day_nunique_calltype_id1_x  day_nunique_calltype_id2_x  day_nunique_calltype_id3  weekday_nunique_calltype_id1_x  weekday_nunique_calltype_id2_x  weekday_nunique_calltype_id3  ...  time_interval_sum_weekday3_y  time_interval_sum_weekday4_y  time_interval_sum_weekday5_y  time_interval_sum_weekday6_y  time_interval_mean_weekday0_y  time_interval_mean_weekday1_y  time_interval_mean_weekday2_y  time_interval_mean_weekday3_y  time_interval_mean_weekday4_y  time_interval_mean_weekday5_y  time_interval_mean_weekday6_y  time_interval_median_weekday0_y  time_interval_median_weekday1_y  time_interval_median_weekday2_y  time_interval_median_weekday3_y  time_interval_median_weekday4_y  time_interval_median_weekday5_y  time_interval_median_weekday6_y  time_interval_max_weekday0_y  time_interval_max_weekday1_y  time_interval_max_weekday2_y  time_interval_max_weekday3_y  time_interval_max_weekday4_y  time_interval_max_weekday5_y  time_interval_max_weekday6_y  time_interval_min_weekday0_y  time_interval_min_weekday1_y  time_interval_min_weekday2_y  time_interval_min_weekday3_y  time_interval_min_weekday4_y  time_interval_min_weekday5_y  time_interval_min_weekday6_y  time_interval_std_weekday0_y  time_interval_std_weekday1_y  time_interval_std_weekday2_y  time_interval_std_weekday3_y  time_interval_std_weekday4_y  time_interval_std_weekday5_y  time_interval_std_weekday6_y  busi_name_count  busi_name_nunique  flow_sum  flow_mean  flow_median  flow_max  flow_min  flow_std  busi_name_count_nunique_ratio  flow_sum_nunique_ratio  label
phone_no_m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ...
22d522340df77e2252c1a4d92b4bcb00d515e36f3ec6bf9...        NaN          NaN           1   9.0                    NaN                      NaN                    NaN                NaN                  NaN             NaN             NaN            NaN                NaN           NaN            NaN              NaN           NaN           NaN           NaN                  NaN                   NaN                     NaN                  NaN                  NaN                  NaN                                  NaN                                 NaN                                 NaN                               NaN                                   NaN                                   NaN                                 NaN                             NaN                             NaN                             NaN                               NaN                               NaN                               NaN                          NaN                          NaN                          NaN                          NaN                          NaN                        NaN                         NaN                         NaN                       NaN                             NaN                             NaN                           NaN  ...                           NaN                           NaN                           NaN                           NaN                            NaN                            NaN                            NaN                            NaN                            NaN                            NaN                            NaN                              NaN                              NaN                              NaN                              NaN                              NaN                              NaN                              NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN              NaN                NaN       NaN        NaN          NaN       NaN       NaN       NaN                            NaN                     NaN      0
5220d4b8429bdba3971a7b46a088c6b8fa6710f40607598...        NaN          NaN           1   NaN                   33.0                     23.0                    1.0                0.0                  0.0             2.0            10.0            4.0                4.0       17866.0     541.393939            240.0        3505.0           2.0    834.616938            1455108.0             45472.125                   412.0            1297878.0                 18.0        229069.824798                             1.434783                                33.0                                 0.0                               0.0                                  23.0                                   0.0                                 0.0                             0.0                             0.0                             0.0                               0.0                               0.0                               0.0                          2.0                          0.0                          0.0                         10.0                          0.0                        0.0                         4.0                         0.0                       0.0                             4.0                             0.0                           0.0  ...                           NaN                           NaN                           NaN                           NaN                            NaN                            NaN                            NaN                            NaN                            NaN                            NaN                            NaN                              NaN                              NaN                              NaN                              NaN                              NaN                              NaN                              NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN                           NaN              NaN                NaN       NaN        NaN          NaN       NaN       NaN       NaN                            NaN                     NaN      1

[2 rows x 1101 columns]

In [20]:
df_test[['label']].to_csv(os.path.join(args.DATA_DIR, 'data_gen/sub04.csv'))

In [19]:
df_test.label.value_counts(dropna=False)

0    1649
1     396
Name: label, dtype: int64

In [26]:
df_test.label.value_counts(dropna=False)

0.0    1380
1.0     585
NaN      80
Name: label, dtype: int64